<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="mvcc-PC" name="BatchExecution_Digi.Hybrid" tests="3" failures="0" timestamp="12 Dec 2017 09:59:22 GMT" time="688.317" errors="2">
  <testcase name="CompanyLogin_CreateSurvey_EditUpdateSurvey_ShareSurvey_EndUSerResponse_ResponseValidationByCompany" time="686.995" classname="BatchExecution_Digi.Hybrid">
    <error type="atu.testng.reports.exceptions.ATUReporterStepFailedException">
      <![CDATA[[ATU Custom Reporter Step Failed Exception]
	at atu.testng.reports.ATUReports.stepFailureHandler(Unknown Source)
	at atu.testng.reports.ATUReports.add(Unknown Source)
	at FunctionalLibraries_Digi.Functional_Libraries.reportstep(Functional_Libraries.java:885)
	at FunctionalLibraries_Digi.Functional_Libraries.ClickByXpath(Functional_Libraries.java:116)
	at Businessfunctions_Digi.Functional_Cases_propread.answer_basedonQueType(Functional_Cases_propread.java:5566)
	at BatchExecution_Digi.Hybrid.CompanyLogin_CreateSurvey_EditUpdateSurvey_ShareSurvey_EndUSerResponse_ResponseValidationByCompany(Hybrid.java:1030)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- CompanyLogin_CreateSurvey_EditUpdateSurvey_ShareSurvey_EndUSerResponse_ResponseValidationByCompany -->
  <testcase name="AdminLogin_CreatingUsers_AdminLogout" time="0.274" classname="BatchExecution_Digi.Hybrid"/>
  <testcase name="CompanyLogin_CreatingUsers_FillingCompanyProfile_FillingMYProfile_CompanyLogout" time="1.048" classname="BatchExecution_Digi.Hybrid">
    <error type="atu.testng.reports.exceptions.ATUReporterStepFailedException">
      <![CDATA[[ATU Custom Reporter Step Failed Exception]
	at atu.testng.reports.ATUReports.stepFailureHandler(Unknown Source)
	at atu.testng.reports.ATUReports.add(Unknown Source)
	at FunctionalLibraries_Digi.Functional_Libraries.reportstep(Functional_Libraries.java:885)
	at FunctionalLibraries_Digi.Functional_Libraries.invokeApplication(Functional_Libraries.java:45)
	at Businessfunctions_Digi.Functional_Cases_propread.companyLogin(Functional_Cases_propread.java:601)
	at BatchExecution_Digi.Hybrid.CompanyLogin_CreatingUsers_FillingCompanyProfile_FillingMYProfile_CompanyLogout(Hybrid.java:205)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- CompanyLogin_CreatingUsers_FillingCompanyProfile_FillingMYProfile_CompanyLogout -->
</testsuite> <!-- BatchExecution_Digi.Hybrid -->
